### ISSUE TITLE
custom cl_viewmodel_ofs for each weapon

### ISSUE THREAD

**Issue by 21Shephard** [Elinsrc/Client-Mod#11]
Is it possible to edit the viewmodel_ofs code separately for each weapon (like cl_viewmodel_ofs_weapon_shotgun)?

**Comment by Elinsrc** [comment]
It can be done, but I won't do it because I'm too lazy.

**Comment by 21Shephard** [comment]
> Yapılabilir, ama yapmayacağım çünkü çok tembelim.

D:
