### ISSUE TITLE
In spectating mode rainbows the nickname when hud_rainbow is enabled

### ISSUE THREAD

**Issue by Vad1mCSO2** [Elinsrc/Client-Mod#14]
![water_canal_0000](https://github.com/user-attachments/assets/c8f5f67f-a32b-48f1-8bad-ba330ac12072)

**Comment by Elinsrc** [comment]
fixed: https://github.com/Elinsrc/Client-Mod/commit/84f68cb36b4cb57f018c4732f40beec1a39aa69b
