### ISSUE TITLE
add a CVAR that displays playerid on HUD

### ISSUE THREAD

**Issue by CHIYUANRAN** [Elinsrc/Client-Mod#18]
![Screenshot_2024-10-31-16-18-03-434_tv.danmaku.bili-edit.jpg](https://github.com/user-attachments/assets/7b6c2f24-450a-4e49-9c41-9086688a107f)

**Comment by Elinsrc** [comment]
what?

**Comment by CHIYUANRAN** [comment]
> what? why is it needed
> 
It's not necessary, but it looks good

**Comment by Elinsrc** [comment]
What does it do? Display your name?

**Comment by CHIYUANRAN** [comment]
> Display

X)
