### ISSUE TITLE
[PC|Windows] Mouse cursor is gone

### ISSUE THREAD

**Issue by Vad1mCSO2** [Elinsrc/Client-Mod#2]
Current Xash3D Version 0.19.2
I'm clicking "Custom Game", selecting mods, click "Activate" and cursor is gone

https://user-images.githubusercontent.com/76803825/168321724-b8eed991-3ce5-4e0f-9da8-76d45dc95331.mp4

!

**Comment by Elinsrc** [comment]
this is weird

**Comment by Elinsrc** [comment]
This is bug old version Xash3d-FWGS.v1.19.*
